services:
  # WordPress with PHP 5.6
  wordpress-php5.6:
    image: wordpress:php5.6
    ports:
      - "8051:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'   # Limits the container to use 0.5 CPU core
          memory: '512M' # Limits the container to use 512MB of memory
    volumes:
      - ./wordpress-php5.6:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db-all
      WORDPRESS_DB_NAME: wordpress56
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    depends_on:
      - db-all

  # WordPress with PHP 7.0
  wordpress-php7.0:
    image: wordpress:php7.0
    ports:
      - "8052:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'   # Limits the container to use 0.5 CPU core
          memory: '512M' # Limits the container to use 512MB of memory
    volumes:
      - ./wordpress-php7.0:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db-all
      WORDPRESS_DB_NAME: wordpress70
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    depends_on:
      - db-all

  # WordPress with PHP 7.4
  wordpress-php7.4:
    image: wordpress:php7.4
    ports:
      - "8053:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'   # Limits the container to use 0.5 CPU core
          memory: '512M' # Limits the container to use 512MB of memory
    volumes:
      - ./wordpress-php7.4:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db-all
      WORDPRESS_DB_NAME: wordpress74
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    depends_on:
      - db-all

  # WordPress with PHP 8.2
  wordpress-php8.2:
    image: wordpress:php8.2
    ports:
      - "8054:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'   # Limits the container to use 0.5 CPU core
          memory: '512M' # Limits the container to use 512MB of memory
    volumes:
      - ./wordpress-php8.2:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db-all
      WORDPRESS_DB_NAME: wordpress82
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    depends_on:
      - db-all

  # MySQL Service
  db-all:
    image: mysql:5.6
    volumes:
      - ./db-all-data:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/my.cnf # Mount custom MySQL config file
    environment:
      MYSQL_ROOT_PASSWORD: password

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8050:80"
    environment:
      PMA_HOSTS: "db-all"  # List all MySQL hosts here
      MYSQL_ROOT_PASSWORD: password
