version: '3.7'

services:
  # WordPress with PHP 5.6
  wordpress-php5.6:
    image: wordpress:php5.6
    ports:
      - "8051:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'   # Limits the container to use 0.5 CPU core
          memory: '512M' # Limits the container to use 512MB of memory
    volumes:
      - ./wordpress-php5.6:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db-php5.6
      WORDPRESS_DB_NAME: wordpress56
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    depends_on:
      - db-php5.6

  # WordPress with PHP 7.0
  wordpress-php7.0:
    image: wordpress:php7.0
    ports:
      - "8052:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'   # Limits the container to use 0.5 CPU core
          memory: '512M' # Limits the container to use 512MB of memory
    volumes:
      - ./wordpress-php7.0:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db-php7.0
      WORDPRESS_DB_NAME: wordpress70
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    depends_on:
      - db-php7.0

  # WordPress with PHP 7.4
  wordpress-php7.4:
    image: wordpress:php7.4
    ports:
      - "8053:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'   # Limits the container to use 0.5 CPU core
          memory: '512M' # Limits the container to use 512MB of memory
    volumes:
      - ./wordpress-php7.4:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db-php7.4
      WORDPRESS_DB_NAME: wordpress74
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    depends_on:
      - db-php7.4

  # WordPress with PHP 8.2
  wordpress-php8.2:
    image: wordpress:php8.2
    ports:
      - "8054:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'   # Limits the container to use 0.5 CPU core
          memory: '512M' # Limits the container to use 512MB of memory
    volumes:
      - ./wordpress-php8.2:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db-php8.2
      WORDPRESS_DB_NAME: wordpress82
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    depends_on:
      - db-php8.2

  # MySQL Service for PHP 5.6
  db-php5.6:
    image: mysql:5.7
    volumes:
      - ./db-php5.6-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  # MySQL Service for PHP 7.0
  db-php7.0:
    image: mysql:5.7
    volumes:
      - ./db-php7.0-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  # MySQL Service for PHP 7.4
  db-php7.4:
    image: mysql:5.7
    volumes:
      - ./db-php7.4-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  # MySQL Service for PHP 8.2
  db-php8.2:
    image: mysql:5.7
    volumes:
      - ./db-php8.2-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8050:80"
    environment:
      PMA_HOSTS: "db-php5.6,db-php7.0,db-php7.4,db-php8.2"  # List all MySQL hosts here
      MYSQL_ROOT_PASSWORD: password
